myproject/myapp/urls.py
from django.urls import path
from . import views


app_name = 'myapp'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('',views.indexview,name='indexview'),
    path('iplist/',views.IPListView.as_view(),name='iplistview'),
    path('ipcreate/',views.IPCreateView.as_view(),name='ipcreateview'),
    path('enablemonitor/',views.enablemonitorview,name='enablemonitorview'),
    path('monitorstart/',views.monitorstartview,name='monitorstartview'),
    path('graph/<int:pk>/',views.graph,name='graph'),
    path('graph/<int:pk>/graph',views.plotgraph,name='plotgraph'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls'))
]

myproject/myapp/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class IPAddress(models.Model):
    address = models.GenericIPAddressField(protocol='both', unpack_ipv4=True, unique=True)
    monitor = models.BooleanField(default=False)

    def __str__(self):
        return str(self.address)

class PingResult(models.Model):
    address = models.ForeignKey(IPAddress, on_delete=models.CASCADE, related_name='ping_results')
    timestamp = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=255)
    response_time = models.FloatField()  # Optional: Store the response time in seconds

    def __str__(self):
        return str(self.address)

myproject/myapp/forms.py
from django import forms
from .models import IPAddress


class IPAddressForm(forms.ModelForm):
    class Meta:
        model = IPAddress
        fields = ['address','monitor']

myproject/myapp/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from .models import IPAddress
from .forms import IPAddressForm
from django.urls import reverse_lazy
from myapp import tasks
from .models import IPAddress, PingResult
from django.http import JsonResponse
from django.utils import timezone

# Create your views here.

def indexview(request):
    return render(request,'index.html')

class IPListView(ListView):
    model = IPAddress
    template_name = 'listipaddress.html'
    context_object_name = 'iplist'

class IPCreateView(CreateView):
    model = IPAddress
    form_class = IPAddressForm
    template_name = 'ip_address_form.html'
    success_url = reverse_lazy('myapp:iplistview')

def monitorstartview(request):
    print("Monitor Starting")
    allip = IPAddress.objects.all()
    for ip in allip:
        tasks.startscheduler(str(ip))
    return render(request,'startmonitor.html')

def enablemonitorview(request):
    return render(request,'enablemonitor.html')

def plotgraph(request, pk=1):
    print("get latency called***************************************")
    print(pk)
    # Get data from the last 24 hours (for example)
    #start_time = timezone.now() - timezone.timedelta(days=1)
    #records = PingResult.objects.filter(timestamp__gte=start_time,address_id=pk).order_by('timestamp')
    records = PingResult.objects.filter(address_id=pk).order_by('timestamp')[:10]

    # Prepare data for JSON response
    timestamps = [record.timestamp.isoformat() for record in records]
    latencies = [record.response_time for record in records]

    print(timestamps)
    data = {
        'timestamps': timestamps,
        'latencies': latencies
    }

    return JsonResponse(data)

def graph(request, pk):
    mydic = {'pk':pk}
    return render(request,'chart.html',mydic)

myproject/templates/base.html
<!DOCTYPE html>

{% load static %}


<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Monitoring Tool</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">

  </head>
  <body>


    <div class="container">
      <div class="jumbotron">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand" href="{% url 'myapp:indexview' %}">Home</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'myapp:iplistview' %}">List IP details</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:ipcreateview' %}">Add new IP</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'myapp:enablemonitorview' %}">Enable Monitoring IP</a>
              </li>



            </ul>
          </div>
        </nav>
      </div>
    </div>


<div class="container">
  <div class="jumbotron">
    <br>
    
    {% block body_block %}





    {% endblock %}
  </div>

</div>


  </body>
</html>

myproject/templates/chart.html
<!-- templates/latency_chart.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Latency Chart</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@1.0.0/dist/chartjs-adapter-date-fns.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/chart.js@3.8.0/dist/chart.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/moment@2.29.1/min/moment.min.js"></script>
     <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-moment@1.0.0/dist/chartjs-adapter-moment.min.js"></script>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body>
    <h1>Latency Over Time</h1>

    <a href="{% url 'myapp:graph' pk %}">Refresh</a>
    <br>
    <a href="{% url 'myapp:iplistview' %}">Back to IPlist page</a>

    <div class="container">
      <div class="jumbotron">
<canvas id="latencyChart" width="100" height="30"></canvas>
      </div>

    </div>

    <h1>Primary Key : {{pk}}</h1>

    <script>
      async function fetchLatencyData() {
            const pk = '{{ pk }}';
            const url = "{% url 'myapp:plotgraph' pk=pk %}";
            const response = await fetch(url);
            if (!response.ok) {
                  throw new Error('Network response was not ok');
              }
            const data = await response.json();
            console.log('Fetched data:', data); // Log data for debugging
            return data;
        }

        async function createChart() {
            const data = await fetchLatencyData();
            if (!data) {
               console.error('No data to display');
               return;
           }
            console.log(data)
            const ctx = document.getElementById('latencyChart').getContext('2d');
            new Chart(ctx, {
                type: 'line',
                data: {
                    labels: data.timestamps,
                    datasets: [{
                        label: 'Latency (ms)',
                        data: data.latencies,
                        borderColor: 'red', //'rgba(75, 192, 192, 1)',
                        backgroundColor: 'rgba(75, 192, 192, 0.2)',
                        borderWidth: 1,
                        pointRadius: 5,
                        pointHoverRadius: 7,
                        fill: false,
                        tension: 0.2
                    }]
                },
                options: {
                    scales: {
                        x: {
                            type: 'time',
                            time: {
                                unit: 'minute',  // or 'hour', 'day', etc., depending on your data range
                                tooltipFormat: 'll HH:mm'
                            },
                            title: {
                                display: true,
                                text: 'Date'
                            }
                        },
                        y: {
                            title: {
                                display: true,
                                text: 'Latency (ms)'
                            }
                        }
                    }
                }
            });
        }
        createChart();
    </script>


</body>
</html>

myproject/templates/enablemonitor.html
{% extends 'base.html' %}



{% block body_block %}

<form method="POST">
  <h1>Do you want to start monitoring</h1>

  <a href="{% url 'myapp:monitorstartview' %}"><input type="button" class="btn btn-success" name="" value="Yes"></a>
  <a href="{% url 'myapp:indexview' %}"><input type="button" class="btn btn-danger" name="" value="No"></a>
</form>

{% endblock %}

myproject/templates/index.html
{% extends 'base.html' %}



{% block body_block %}
{% load static %}

<h1>Welcome to Monitoring tool</h1>

{% endblock %}

myproject/templates/ip_address_form.html
{% extends 'base.html' %}




{% block body_block %}

<form  method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Save</button>
</form>


{% endblock %}

myproject/templates/listipaddress.html
{% extends 'base.html' %}



{% block body_block %}

<h1> List of IP details below </h1>
<table>
    <thead>
        <tr>
            <th>PK</th>
            <th>IP Address</th>
            <th>Monitoring</th>
        </tr>
    </thead>

    <tbody>
      {% for ip in iplist %}
        <tr>
            <td>{{ ip.pk }}</td>
            <td><a href="{% url 'myapp:graph' ip.pk %}">{{ ip.address }}</a></td>
            <td> {{ ip.monitor|yesno:"Yes,No" }}</td>
        </tr>
    </tbody>

{% endfor %}




{% endblock %}

myproject/templates/startmonitor.html
{% extends 'base.html' %}



{% block body_block %}


<h1>Monitoring Started</h1>

{% endblock %}